use_frameworks!

target 'DecouplerKit_Example' do
  pod 'DecouplerKit', :path => '../'
  pod 'RealmSwift'
  target 'DecouplerKit_Tests' do
    inherit! :search_paths
    pod 'DecouplerKit', :path => '../'
  end
end
